katalog/fluentd/fluent.conf

Fluentd - parsing of nginx-ingress logs

---

.drone.yml
README.md
katalog/tests/tests.bats

Hi team. 
I have tested this package against three kubernetes releases, 1.14, 1.15 and 1.16, (last revision) and it works. So i updated the compatibility chart adding the needed steps in the pipeline.
If you've got any doubt, let me know ;)
Thanks!

Add more K8S testing environments

---

.drone.yml
README.md
docs/releases/v1.2.0.md
docs/releases/v1.2.1.md
katalog/tests/tests.bats

Hi team. 
When i were looking for the latest release available in this package I have encountered:
1. Latest version: v1.2.0 is not listed in the compatibility Matrix.
2. The v1.2.0 Pipeline failed. So i don't know if v1.2.0 is stable.
I think v1.2.0 pipeline failed because of the "legacy" way of testing. This core module needs a lot of resources to run while the CI instance can't provide it. This is why i have created this PR:
1. Moved from "legacy" testing method to cloud one.
2. Activated previously deactivated tests *(mostly sure were deactivated due to the lack of resources)*.
Now, we can confirm the code works. (I have passed a pipeline (forcing it) to verify it).
Learning notes:
Please, if you create a release, create the compatibility matrix row associated to that release. We have …

Solve/Refactor E2E Testing

---

docs/releases/v1.3.1.md
katalog/elasticsearch-single/README.md
katalog/elasticsearch-single/kustomization.yaml
katalog/elasticsearch-single/rules.yml

Hi guys, thanks to @lzecca78 i added some prometheus rules on elasticsearch!
This PR should address the issue #4

Adding prometheus rules to elasticsearch.

---

.bumpversion.cfg
.drone.yml
README.md
docs/releases/v1.5.0.md
examples/cerebro-deployment/Furyfile.yml
examples/elasticsearch-resources/Furyfile.yml
examples/kibana-node-selector/Furyfile.yml

Hi team!
This PR tests the current module against Kubernetes 1.17 and 1.18 (on vsphere).
It seems to be working: http://ci.sighup.io/sighupio/fury-kubernetes-logging/235/4/3
Thanks!

Prepare release v1.5.0

---

docs/releases/unreleased.md
katalog/cerebro/cerebro.yml

Hi all 👋 
I'm opening this little PR to reduce cerebro requests in cpu and memory (is too high on not so big clusters)

Reducing Cerebro cpu and memory requests

---

examples/registry-override/README.md
examples/registry-override/cerebro/kustomization.yaml
examples/registry-override/curator/kustomization.yaml
examples/registry-override/elasticsearch-single/kustomization.yaml
examples/registry-override/elasticsearch-triple/kustomization.yaml
examples/registry-override/fluentd/kustomization.yaml
examples/registry-override/kibana/kustomization.yaml
katalog/cerebro/cerebro.yml
katalog/cerebro/kustomization.yaml
katalog/curator/curator.yml
katalog/curator/kustomization.yaml
katalog/elasticsearch-single/elasticsearch.yml
katalog/elasticsearch-single/kustomization.yaml
katalog/elasticsearch-single/ns.yml
katalog/elasticsearch-single/sm.yml
katalog/elasticsearch-triple/kustomization.yaml
katalog/elasticsearch-triple/triple.yml
katalog/fluentd/fluentbit.yaml
katalog/fluentd/fluentd.yml
katalog/fluentd/kustomization.yaml
katalog/fluentd/rbac.yml
katalog/fluentd/sm.yml
katalog/kibana/kibana.yml
katalog/kibana/kustomization.yaml

Following #27 created an example folder with all the possible image override needed (if someone is self hosting on another registry and so on)

Example on registry override

---

.bumpversion.cfg
.drone.yml
.rules/kustomization.rego
Makefile
build/builder/Dockerfile
docs/CONTRIBUTING.md
katalog/cerebro/kustomization.yaml
katalog/curator-s3/kustomization.yaml
katalog/curator/kustomization.yaml
katalog/elasticsearch-single/kustomization.yaml
katalog/elasticsearch-triple/kustomization.yaml
katalog/fluentd/kustomization.yaml
katalog/kibana/kustomization.yaml

This PR adds the `KFD` labels to each of the components in the module.
PS: This PR is rebase with #49 , the commits regarding adding Makefile hence is from that.

Add KFD labels to all module components

---

.drone.yml
README.md
examples/fluent-bit-deployment/deploy.yml
katalog/curator-s3/kustomization.yaml
katalog/elasticsearch-single/README.md
katalog/elasticsearch-single/kustomization.yaml
katalog/fluentd/README.md
katalog/fluentd/kustomization.yaml
katalog/kibana/README.md
katalog/kibana/kustomization.yaml

`e2e-tests` passed for these versions here: http://ci.sighup.io/sighupio/fury-kubernetes-logging/670

Upgrade the images for the logging module

---

katalog/fluentd/fluent.conf

Useful change for using Signals or fluent-ctl
ref:
https://docs.fluentd.org/deployment/signals

Set human readable fluentd process name

---

katalog/kibana/kibana.yml

Hi team, i did a little change to remove the index pattern injection from readiness Probe to a sidecar container.
As soon as the index pattern is injected, the sidecar will stop doing curl.

Improve kibana index pattern injection via sidecar, remove readinessProbe

---

docs/releases/v2.0.1.md
katalog/configs/ingress-nginx/flow.yml
katalog/configs/kubernetes/cluster-flow.yml
katalog/logging-operated/fluentd-fluentbit.yml

[HOTFIX] - Update fluent-bit on logging-operated to ver 1.8.15, fix ingress flow matching on dual nginx

---

.drone.yml

This PR adds the support and testing for Kubernetes 1.24
https://ci.sighup.io/sighupio/fury-kubernetes-logging/1195/7/3 step 1.24 has passed ✅

[Feature] - add 1.24 support

---

katalog/logging-operated/minio/init-job.yaml
katalog/logging-operated/minio/kustomization.yaml

This PR addresses the issue #76 , fixing the conflicts on kustomize side

[HOTFIX] - minio incompatibility with velero on prem

---

docs/releases/v2.0.3.md

As per title, adding release notes for 2.0.3

feat: release 2.0.3

---

docs/COMPATIBILITY_MATRIX.md
docs/releases/v3.0.1.md

docs: add release note and compatibility matrix entry for 3.0.1

---

katalog/configs/audit/audit-index-template.json
katalog/configs/events/events-index-template.json
katalog/configs/ingress-nginx/ingress-controller-index-template.json
katalog/configs/kubernetes/kubernetes-index-template.json
katalog/configs/systemd/common/systemd-index-template.json

replace 'number_of_replicas' with 'auto_expand_replicas' into index templates

feat: replace 'number_of_replicas' with 'auto_expand_replicas' into

---

README.md
examples/tolerations/README.md
examples/tolerations/configs/kubernetes-event-tailer.yml
examples/tolerations/configs/kustomization.yaml
examples/tolerations/logging-operated/fluentd.yml
examples/tolerations/logging-operated/kustomization.yaml
examples/tolerations/logging-operated/minio.yml
examples/tolerations/logging-operator/kustomization.yaml
examples/tolerations/logging-operator/logging-operator.yml

Hello guys,
I've added some examples to specify tolerations and node selectors in the logging operator and its CRDs.

Add examples/tolerations

---

docs/COMPATIBILITY_MATRIX.md
docs/releases/v3.0.3.md
katalog/opensearch-single/deploy.yaml

Hotfix - update release 3.0 with hotfix on opensearch start

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v3.1.2.md
katalog/logging-operated/MAINTENANCE.md
katalog/logging-operated/README.md
katalog/logging-operated/dashboards/dashboard-logging.json

update Grafana dashboard included with the loggin-operated package, the provided one was outdated and using metrics that are not available anymore.

fix(logging-operated): update grafana dashboard

---

katalog/opensearch-dashboards/MAINTENANCE.md
katalog/opensearch-dashboards/README.md
katalog/opensearch-dashboards/kustomization.yaml
katalog/opensearch-single/MAINTENANCE.md
katalog/opensearch-single/README.md
katalog/opensearch-single/deploy.yaml
katalog/opensearch-single/kustomization.yaml
katalog/opensearch-single/sm.yml
katalog/opensearch-triple/README.md

Reverts sighupio/fury-kubernetes-logging#142

Revert "Feature/212 update opensearch n opendashboard 1 26"

---

katalog/loki-distributed/MAINTENANCE.md
katalog/loki-distributed/README.md
katalog/loki-distributed/deploy.yml
katalog/loki-distributed/kustomization.yaml

- Update the loki version to 2.8.0
- Update helm annotation
- add 'helm repo update' in the maintenance guide

feat(loki): version bump v2.8.0

---

README.md
katalog/opensearch-dashboards/MAINTENANCE.md
katalog/opensearch-dashboards/README.md
katalog/opensearch-dashboards/kustomization.yaml
katalog/opensearch-single/MAINTENANCE.md
katalog/opensearch-single/README.md
katalog/opensearch-single/kustomization.yaml
katalog/opensearch-triple/README.md

Upgrade opensearch v2.11

---

katalog/kibana/kibana.yml

Hi everyone 👋 ,
as described herehttps://www.elastic.co/guide/en/kibana/7.16/production.html#memory,
the parameter "--max-old-space-size" shouldn't be specified because it is dynamically set accordingly to the allocated resources.
The hardcoded parameter caused several error like this one:
```
Error: Invalid string. Length must be a multiple of 4
```
and as consequence a stacktrace of the java process:
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb02ec0 node::Abort() [/usr/share/kibana/bin/../node/bin/node]
2: 0xa181fb node::FatalError(char const*, char const*) [/usr/share/kibana/bin/../node/bin/node]
3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/share/kibana/bin/../node/bin/node]
4: 0xcedc07 …
```

Removing hardcoded environment variable in Kibana

---

katalog/opensearch-dashboards/MAINTENANCE.md
katalog/opensearch-dashboards/kustomization.yaml
katalog/opensearch-single/MAINTENANCE.md
katalog/opensearch-single/README.md
katalog/opensearch-single/deploy.yaml
katalog/opensearch-single/kustomization.yaml
katalog/opensearch-triple/README.md

- update to opensearch v2.12.0
- update opensearch-dashboards v2.12.0
- update maintenance guides
Resolves https://github.com/sighupio/product-management/issues/388

feature(opensearch): update to v2.12.0

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v3.4.1.md

feat: add release notes and update compatibility matrix/readme v3.4.1

---

.drone.yml
katalog/tests/tests.sh

feat(ci): add new loki resources to tests
