sighupio/module-logging

katalog/fluentd/deploy.yml
The set of tolerations of fluentd daemonset is too restricted, in this way it'll tolerate any taint applied to nodes and won't need "special" Kustomize patches to get correctly scheduled.
=> increased fluentd daemonset tolerations

docs/releases/unreleased.md, katalog/fluentd/fluentd.yml
Spotted by the delivery team, fluentd can run in master nodes. Witch, it is not intended.
With this simple PR we fix that behavior!
As remediation (suggested by @nutellinoit) create a patch with some tolerations like:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: fluentd
namespace: logging
spec:
template:
spec:
nodeSelector:
node-role.kubernetes.io/infra: ""
tolerations:
- key: node-role.kubernetes.io/infra
operator: Exists
effect: NoSchedule
```
Thanks!
=> Remove tolerations to fluentd sts, avoid to run on master

.rules/.luacheckrc, katalog/fluentd/fluent-bit.conf, katalog/fluentd/fluentbit.yaml, katalog/fluentd/kustomization.yaml, katalog/fluentd/scripts/dedot.lua
Hi team, i added a little lua script on fluentbit to dedot labels and annotations before sending data to fluentd.
Source here: https://github.com/fluent/fluent-bit/issues/1134#issuecomment-592959828
This way, there will be no conflict on elasticsearch side because everything will be a string instead of an object.
I tested it and it's working, but before merging or do more test (eg on a real cluster) tell me what you think about it
=> Dedot fluentbit filter for labels and annotations

katalog/kibana/config/index-patterns.ndjson, katalog/kibana/kibana.yml, katalog/kibana/kustomization.yaml
Hi @everyone 👋 !
This PR wants to introduce the creation of kibana index-patterns directly from a configuration file. The reason of putting the HTTP post in the readinessProbe is because the service must be up and running and kibana takes minutes to do that, so there isn't other good alternative( probably one alternative could be a job, but the job should check the readiness of the kibana service, so could be an overengineering of the current implementation).
Well, if you have good alternative, please write down 👇  any further suggestions!
=> added capability to create index-pattern from configuration file

katalog/fluentd/conf.d/audit-output.conf, katalog/fluentd/conf.d/ingress-controller-output.conf, katalog/fluentd/conf.d/kubernetes-output.conf, katalog/fluentd/conf.d/system-output.conf, katalog/fluentd/fluentd-index-sighup-template-audit.json, katalog/fluentd/fluentd-index-sighup-template-ingress-controller.json, katalog/fluentd/fluentd-index-sighup-template-kubernetes.json, katalog/fluentd/fluentd-index-sighup-template-system.json, katalog/fluentd/fluentd.yml, katalog/fluentd/kustomization.yaml
Hi team, little PR to enhance the template management, one file for each index stream and a little param change to suppress the `_doc` field when sending logs on ES.
Right now fluentd is emitting warn on stdout:
```txt
fluentd-0 fluentd warning: 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa "[types removal] Specifying types in bulk requests is deprecated."
```
=> Differentiate templates for each stream, suppress ES 7 warn on fluentd

docs/releases/unreleased.md, katalog/kibana/kibana.yml
Hi team! 
Another little PR, changing kibana strategy due to some indexes migration problems (.kibana being stuck, etc) and changing cpu limits to 2, because when kibana starts, there is a lot of Javascript compling and some heavy cpu stuff, causing .kibana indexes to not migrate or being stuck in a broken state
=> Changing update strategy to Recreate and changing cpu limits to 2 cores

docs/releases/unreleased.md, katalog/kibana/kibana.yml
Hi team, we found that the new readinessProbe creates some flapping on kibana pod, usually when someone is using Kibana.
I changed the probe that installs index patterns as a startupProbe and replaced the readinessProbe with the old one.
startupProbe is beta from 1.18, and graduated to GA in 1.20
=> Moved readiness probe as startup probe. Reverted readiness probe to check only Kibana status

katalog/fluentd/fluent.conf
warn message fixed:
define <match fluent.**> to capture fluentd logs in top level is deprecated.
Use <label @FLUENT_LOG> instead.
Relevant documentation:
https://docs.fluentd.org/deployment/logging#capture-fluentd-logs
=> Update config that prevents fluentd from capturing own logs

katalog/fluentd/conf.d/audit-output.conf, katalog/fluentd/conf.d/ingress-controller-output.conf, katalog/fluentd/conf.d/kubernetes-output.conf, katalog/fluentd/conf.d/system-output.conf, katalog/fluentd/fluent.conf
Use warning log level as error level was hiding
fluentd logs that were highlighting log rejecionts
by ElasticSearch.
Set both at the global and at the plugin level
ref:
https://docs.fluentd.org/deployment/logging#per-plugin-log
=> Change default logging level from error to warn

katalog/fluentd/fluent.conf
Use @label routing (@ES and @ERROR) to send
malformed logs to the /buffers/errors thus
avoiding the situation where buffers get filled
with malformed logs causing the logging stack
to stop working.
ref:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.Troubleshooting.md#using-label-feature
=> Use @label routing

.bumpversion.cfg, .drone.yml, README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v1.10.0.md, docs/releases/v1.10.1.md, docs/releases/v1.10.2.md, docs/releases/v1.9.2.md, examples/cerebro-deployment/Furyfile.yml, examples/curator-s3-deployment-with-jaeger/Furyfile.yml, examples/curator-s3-deployment/Furyfile.yml, examples/elasticsearch-resources/Furyfile.yml, examples/kibana-node-selector/Furyfile.yml, katalog/cerebro/kustomization.yaml, katalog/curator-s3/kustomization.yaml, katalog/curator/kustomization.yaml, katalog/elasticsearch-single/kustomization.yaml, katalog/elasticsearch-triple/kustomization.yaml, katalog/fluentd/kustomization.yaml, katalog/kibana/kustomization.yaml
As per title, we need to remove all `commonLabels` from katalog packages, these labels are breaking the upgrade path for future releases
=> [HOTFIX] - commonLabels removal

katalog/kibana/config/index-patterns.ndjson, katalog/kibana/kibana.yml
this will enable kibana to waste less resource on unused plugin in the background and will also help with a correct dimension of heap memory.
new indexpattern will be default in the future since we added the eventlogger on our logging module.
all of this can be easily tuned by a patch.
=> fix (kibana): disable unused plugin and add event indexpattern

README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v2.0.2.md, katalog/configs/audit/audit-hosttailer.yml, katalog/logging-operated/fluentd-fluentbit.yml, katalog/logging-operator/README.md, katalog/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_flows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_loggings.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_outputs.yaml, katalog/logging-operator/deploy.yaml, katalog/logging-operator/kustomization.yaml
This PR addresses the problem of the stale SA that fluentbit uses. 
> This problem occours since Kubernetes 1.21 changed the way Service Accounts work. Service accounts are auth tokens used by applications to talk with the masters. Up until Kubernetes 1.20, Service Accounts did NOT expire. From K8s 1.21, Service Accounts are set to expire. This will cause applications using expired tokens to stop working
=> feat(fluentbit): backporting fluent bit 1.9.5 sa problem to v2.0

katalog/opensearch-single/MAINTENANCE.md, katalog/opensearch-single/rules.yml
Align the field used to describe the alert with what we are using in the rest of the alerts and in the AlertManager template for the Slack notifications.
=> fix(monitoring): fix description field for alerts

katalog/configs/audit/audit-hosttailer.yml, katalog/configs/systemd/etcd/hosttrailer.yml
Kubeadm for v1.24 and afterwards changed the taint of the master nodes from `master` to `control-plane`.
Switch nodeSelector to Affinity to be able to include both cases (nodeSelector only allows AND conditions).
Fixes #97
=> fix(configs): use Affinity instead of nodeSelector

katalog/loki-configs/README.md
specify that the loki-configs is configs for Loki and not the same as configs.
=> docs(loki-configs): fix title

katalog/opensearch-single/deploy.yaml
This change adds some logic when changing max_map_count and file-max sysctl values, only whn the pre-existing value is lower than a treshold.
Modern systems already have higher values in place, eg: EKS.
=> feat: improve opensearch initContainer

katalog/configs/audit/output.yml, katalog/configs/events/output.yml, katalog/configs/ingress-nginx/output.yml, katalog/configs/kubernetes/cluster-flow.yml, katalog/configs/kubernetes/cluster-output.yml, katalog/configs/systemd/etcd/output.yml, katalog/logging-operated/fluentd-fluentbit.yml
This PR improves how we manage `@ERROR` logs. 
First change is to enable the opensearch outputs to log 400 errors with log_os_400_reason: true
The second change is to suppress the parse error when the log is not in JSON format on kubernetes flow (this was sent to `@ERROR` but is not a real error
The third change is to set logLevel: debug on fluentd, to enable emitting 400 errors as @ERROR , see: https://github.com/fluent/fluent-plugin-opensearch#log_os_400_reason 
I was not able to have fluentd logs on stdout, maybe there is a bug, but this change will reduce massively the @ERROR to the minio instances.
=> Feat: improve @ERROR handling

.drone.yml, katalog/logging-operated/README.md, katalog/logging-operated/fluentd-fluentbit.yml, katalog/logging-operator/MAINTENANCE.md, katalog/logging-operator/README.md, katalog/logging-operator/crds/logging-extensions.banzaicloud.io_eventtailers.yaml, katalog/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_flows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_loggings.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_outputs.yaml, katalog/logging-operator/deploy.yaml, katalog/logging-operator/kustomization.yaml
e2e is failing on opensearch, I already tested logging operator on a 1.25 cluster
=> feat: update logging operator to the latest stable version test it with k8s 1.25

katalog/logging-operated/minio/sts.yaml, katalog/opensearch-dashboards/MAINTENANCE.md, katalog/opensearch-dashboards/README.md, katalog/opensearch-dashboards/deploy.yaml, katalog/opensearch-dashboards/kustomization.yaml, katalog/opensearch-single/MAINTENANCE.md, katalog/opensearch-single/README.md, katalog/opensearch-single/deploy.yaml, katalog/opensearch-single/kustomization.yaml
As per title this PR updates opensearch and opensearch dashboards to 2.5.0 version.
Also, I included a little fix on the minio console port (found while testing)
=> Feat: update opensearch and opensearch dashboards to the latest stable version test it with k8s 1.25

katalog/configs/infra/cluster-output.yml, katalog/configs/ingress-nginx/flow.yml
Hi everyone 👋 ,
this draft will aim to introduce a more fine-grade and error-prone parser, accordingly with what we've experienced in several client. With the `multi_format` plugin, is possible to specify multiple patterns (one for the default nginx controller log format, the other for the error log).
Feel free to adapt/correct/request changes if you see something wrong.
Is a draft because i still need to test it deeply.
Fixes #120
=> nginx double logging format

README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v3.0.2.md, katalog/configs/audit/audit-index-template.json, katalog/configs/audit/output.yml, katalog/configs/events/events-index-template.json, katalog/configs/events/output.yml, katalog/configs/ingress-nginx/flow.yml, katalog/configs/ingress-nginx/ingress-controller-index-template.json, katalog/configs/ingress-nginx/output.yml, katalog/configs/kubernetes/cluster-flow.yml, katalog/configs/kubernetes/cluster-output.yml, katalog/configs/kubernetes/kubernetes-index-template.json, katalog/configs/systemd/common/systemd-index-template.json, katalog/configs/systemd/etcd/output.yml, katalog/logging-operated/fluentd-fluentbit.yml, katalog/logging-operated/minio/cronjob.yaml, katalog/logging-operated/minio/kustomization.yaml, katalog/logging-operated/minio/sts.yaml
This PR address these features/hotfixes
- Changed the Fluentd log level to debug and enabled `log_os_400_reason: true` on all OpenSearch outputs so that rejected logs from OpenSearch are labeled @ERROR and captured on Minio.
- Added a retention of 7 days for saved objects on Minio.
- Removed the emission of `@ERROR` logs that cannot be parsed in JSON from ClusterFlow Kubernetes.
Everything was taken from the current main iteration and adapted for the 3.0.x
=> Hotfix - update release3.0 with hotfixes and enhancement, version 3.0.2

katalog/logging-operated/dashboards/kustomization.yaml, katalog/loki-distributed/datasource/kustomization.yaml
Add annotation to put the module's Grafana dashboards inside the "Logging" folder for better organization.
=> feat: put dashboards in "Logging" grafana folder

.drone.yml, README.md, docs/COMPATIBILITY_MATRIX.md, docs/releases/v3.2.1.md, katalog/logging-operated/fluentd-fluentbit.yml, katalog/tests/tests.sh
Reverted fluentd to v1.14 due to a [bug](https://github.com/opensearch-project/opensearch-ruby/issues/205).
=> fix(logging-operated): revert fluentd v1.14 + docs

.drone.yml, katalog/tests/kind/config.yml
Add tests for Kubernetes 1.28 and 1.29, remove 1.25.
Run e2e tests on a Kind cluster running on the drone worker instead of creating a dedicated VM on VMware. E2E tests running time is reduced by more than half (~20 mins to <10 min).
> [!NOTE]
> The last step of a `tag` pipeline is failing on purpose, we don't need to test the release itself
**Documentation will be updated in a following PR.**
Resolves https://github.com/sighupio/product-management/issues/391
Resolves https://github.com/sighupio/product-management/issues/390
=> chore(ci/e2e): K8s 1.28 & 1.29, use Kind on baremetal

.drone.yml, katalog/loki-distributed/MAINTENANCE.md, katalog/loki-distributed/MAINTENANCE.values.yaml, katalog/loki-distributed/README.md, katalog/loki-distributed/deploy.yml, katalog/tests/kind/config.yml
- update manifests to align with latest chart version from upstream (v0.78.1).
- update maintenance guide with some more details.
- update maintenance values.yaml file to minimize manual changes.
> [!NOTE]
> `compactor` has been changed to a StatefulSet in v0.78.0 of the Helm Chart but can still be installed as a deployment. I've updated the maintenance values.yaml file to keep the deployment mode for backwards compatbility.
There are no substantial functional changes. Components versions remain the same.
> [!WARNING]
> This PR is branched from https://github.com/sighupio/fury-kubernetes-logging/pull/160
Resolves https://github.com/sighupio/product-management/issues/387
=> feat(loki-distributed): update to chart v0.78.1

README.md, katalog/logging-operated/MAINTENANCE.md, katalog/logging-operated/README.md, katalog/logging-operated/fluentd-fluentbit.yml, katalog/logging-operator/MAINTENANCE.md, katalog/logging-operator/README.md, katalog/logging-operator/crds/kustomization.yaml, katalog/logging-operator/crds/logging-extensions.banzaicloud.io_eventtailers.yaml, katalog/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_flows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_loggings.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_outputs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_syslogngclusterflows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_syslogngconfigs.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_syslogngflows.yaml, katalog/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml, katalog/logging-operator/deploy.yaml, katalog/logging-operator/kustomization.yaml
This PR includes:
- update logging-operator to v4.5.6:
- updated manifests
- updated CRDs and added 2 new ones
- removed custom option `PSP_ENABLED` because a fix has been included since v4.4.0
- update logging-operated to use the new fluentd version compatible with logging-operator v4.5.6
- update maintenance guide
- update readmes
Some notes:
- Here are the main changes in this new version: https://kube-logging.dev/docs/whats-new/ . TL;DR is:
> Starting with Logging operator version 4.5, you can either configure Fluentd in the `Logging` CR, or you can use a standalone `FluentdConfig` CR. Similarly, you can use a standalone `SyslogNGConfig` CRD to configure syslog-ng.
- The `logging-operated` package coudl use the new FluentdConfig CR but I chose not to to simplify the ugprade process. …
=> feat(logging-operator,logging-operated): update logging-operator to v4.5.6, align logging-operated

katalog/logging-operated/fluentd-fluentbit.yml
This PR includes:
- restore persistent `positiondb`
- add the field `enableRecreateWorkloadOnImmutableFieldChange` as true in order to enable the operator to recreate resources in case there is a change in an immutable field
Tested the upgrade from the previous version with Kubernetes 1.28.
=> fix(logging-operated): add positiondb, enable operator to recreate resources

katalog/opensearch-dashboards/index-patterns-cronjob.yml, katalog/opensearch-single/ism-policy-cronjob.yml
This PR adds labels for opensearch and opensearch-dashboard cronjob pods that will be needed by Network Policies to manage traffic between pods.
=> chore(opensearch/opensearch-dashboards): add labels for jobtemplate

katalog/opensearch-single/deploy.yaml, katalog/opensearch-single/kustomization.yaml
This PR updates the es search exporter to the v1.8.0 version using the image maintained by the prometheus community. Closes #168
=> feat(opensearch): update es exporter to v1.8.0

katalog/configs/events/kubernetes-eventtailer.yml
Since switching to images from kube-logging instead of the ones from Banzai Cloud, upstream image tags don't have the `v` in front anymore:
https://github.com/kube-logging/eventrouter/pkgs/container/eventrouter/118063456?tag=0.4.0
(upstream taken from our image-sync repository)
Ref:
- https://github.com/sighupio/fury-distribution-container-image-sync/pull/191
=> fix(configs/eventtailer): use right tag for image

docs/releases/unreleased.md, katalog/minio-ha/MAINTENANCE.md, katalog/minio-ha/MAINTENANCE.values.yaml, katalog/minio-ha/deploy.yaml, katalog/minio-ha/kustomization.yaml
Update `minio-ha` images to their latest versions
Closes: [#569](https://github.com/sighupio/product-management/issues/569)
- Updated `minio` chart to `5.4.0`
- Updated `minio` image tag to `RELEASE.2025-02-28T09-55-16Z`
- Updated `minio/mc` image tag to `RELEASE.2025-02-21T16-00-46Z`
- Updated MAINTENANCE.md guidelines with more precise instructions
- Moved version pinning from `kustomization.yaml` to setting the related values when templating from Helm
None
=> feat: update minio deployment to the latest version same version on all modules

docs/releases/unreleased.md, katalog/loki-distributed/configs/config.yaml
This pull request sets a default retention period of 30 days for the Loki stack.
Relates: [sighupio/module-logging/issues/177](https://github.com/sighupio/module-logging/issues/177)
The change includes:
- Support for global retention via the `retention_period` setting under `limits_config`
- Usage of the existing `persistentvolumeclaim/data-loki-distributed-compactor` as the working directory for the compactor
None
None
=> feat(loki): add default retention

README.md, docs/releases/unreleased.md, katalog/configs/README.md, katalog/configs/audit/output.yml, katalog/configs/events/output.yml, katalog/configs/infra/cluster-output.yml, katalog/configs/ingress-nginx/output.yml, katalog/configs/kubernetes/cluster-output.yml, katalog/configs/systemd/common/output.yml, katalog/configs/systemd/etcd/output.yml, katalog/logging-operated/README.md, katalog/logging-operated/fluentd-fluentbit.yml, katalog/loki-configs/README.md, katalog/loki-configs/audit/output.yml, katalog/loki-configs/events/output.yml, katalog/loki-configs/infra/cluster-output.yml, katalog/loki-configs/ingress-nginx/output.yml, katalog/loki-configs/kubernetes/cluster-output.yml, katalog/loki-configs/systemd/common/output.yml, katalog/loki-configs/systemd/etcd/output.yml
This PR:
- Increases the default resources limits and requests for fluentd and fluentbit, based on behaviour that we've been seeing on production clusters.
- Adds where missing and increases when present the `flush_thread_count` parameter in the Configs and Loki Configs.
Increases the default resources limits and requests for fluentd and fluentbit, based on behaviour that we've been seeing on production clusters.
Note that this value tempts to be a better default but tailored configuration may be still needed for each cluster.
Adds where missing and increases when present the value of `flush_thread_count` in both the (OpenSearch) Configs and Loki Configs, so fluentd flushing to remote storage is faster and not limited to a single thread.
This was particularly bad for Loki Configs, because …
=> feat: increase default resources and thread count

katalog/configs/kubernetes/cluster-flow.yml
Remove JSON parser from the kubernetes flow.
Fixes #197
Remove JSON parser from the kubernetes flow.
Being that the kubernetes flow picks up logs from all the applicative workload, that we can't know before hand, it does not make sense to have the JSON parser with a predefined key (`message`) that may or may not exist.
When the key does not exists but logs have JSON format the parser does not detect properly the date falling back to the epoch (1970-01-01).
The parser has been added by [this commit](https://github.com/sighupio/module-logging/commit/fc4608b2b83ea9ff3ac0b7188e55f6cbf9fdf71b) with a comment saying that it was needed to parse containerd logs, but containerd logs are no in the kubernetes flow, they are picked up by the systemd flows.
None
None
=> fix(configs): remove json parser from kubernetes flow
